## Configuring info endpoint
info:
  app:
    name: product-service
    description: Product management microservice
    version: 1.0.0

management:
  endpoints:
    web:
      base-path=/details:
      exposure:
        include: "health, info"
  endpoint:
    jackson:
      isolated-object-mapper: true
    health:
      show-details: always
    info:
      env:
        enabled: true
      build:
        enabled: true

spring:
  application:
    name: spring-boot-redis-cache
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
  data:
    redis:
      host:localhost
      port:6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql:true
