info:
  app:
    name: product-service
    version: 1.0.0
    description: Product management microservice

management:
  endpoints:
    web:
      exposure:
        include: info

spring:
  application:
    name: spring-boot-redis-cache
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql:true
